### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by pauloarn** [dkjroot/iris-llm#1]
I haven't figured out how can i set it up localy.

Does it have a "setup-for-dummies"?

**Comment by pauloarn** [comment]
I had some improvments, installed manually the dependencies but now i'm getting this error:

```C:\Users\paulo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
C:\Users\paulo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydub\utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "D:\PersonalDev\OPEN AI\PERSONAL ASSISTANT\iris-llm\iris.py", line 39, in <module>
    sounds_module = importlib.import_module(settings['feedback sounds'])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paulo\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\PersonalDev\OPEN AI\PERSONAL ASSISTANT\iris-llm\iris_sounds\beeps_and_bleeps.py", line 9, in <module>
    class Sounds(ISounds):
  File "D:\PersonalDev\OPEN AI\PERSONAL ASSISTANT\iris-llm\iris_sounds\beeps_and_bleeps.py", line 10, in Sounds
    working = AudioSegment.from_mp3('iris_sounds/workinglongquiet.mp3')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paulo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydub\audio_segment.py", line 796, in from_mp3
    return cls.from_file(file, 'mp3', parameters=parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paulo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paulo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paulo\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\paulo\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado```

**Comment by dkjroot** [comment]
Hi!  Sorry I've kind of abandoned this - I've been so busy lately.  If you check out the prototypes branch it's very step-by-step in there, and is intended as a tutorial (this file https://github.com/dkjroot/iris-llm/blob/prototypes/examples/README.md).  It might be out of date by now though, but it possibly still works.  Unfortunately though I did assume that readers would have the python background to figure out the dependencies for themselves, I didn't go into that side of it very much.  That error looks like you need to install ffmpeg and make sure the dll file is on your path.  Hope that helps!
